#
# Jekyll Config
# 


# Data Model
collections:
  articles:
    title: Articles
    output: true
  topics:
    title: Topics
    output: true


# Defaults
defaults:
  -
    scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "article"
  -
    scope:
      path: "_topics"
      type: "topics"
    values:
      layout: "topic"


# Site settings
name: Hamon
permalink: :slug
timezone: Asia/Kolkata
baseurl: ""


# Build settings
source: ./templates
destination: ./_site
keep_files:
  - build
  - js
  - img
markdown_ext: "markdown,mkdown,mkdn,mkd,md,liquid"

